plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-3.5.0.cjs
# npmScopes:
#   totalsoft:
#     npmRegistryServer: https://registry.npmjs.org/
#     npmAuthToken: ${NODE_AUTH_TOKEN}
#     npmAlwaysAuth: true
