# This workflow will run tests using node and then publish a package to NPM when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: npm-publish

on:
  release:
    types: [published]

concurrency:
  group: build-test-publish

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/
          scope: '@totalsoft'
      - run: yarn -v
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      # - name: Run tests
      #   run: yarn test
      - name: Bump version
        run: yarn run version
      - name: Authenticate yarn berry to npm
        run: yarn config set npmPublishRegistry 'https://registry.npmjs.org/'
      - shell: Set npm authToken from env
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn config
          yarn config set npmScopes.company.npmRegistryServer "https://registry.npmjs.org/"
          yarn config set npmScopes.company.npmAlwaysAuth true
          yarn config set npmScopes.company.npmAuthToken $NODE_AUTH_TOKEN
      - run: yarn publish
        # env:
        #   NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
