# This workflow will run tests using node and then publish a package to NPM when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: npm-publish

on:
  release:
    types: [published]

concurrency:
  group: build-test-publish

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Run tests
        run: yarn test
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/
          scope: '@totalsoft'
      - run: yarn -v
      - name: Bump version
        run: yarn run version
      - uses: borales/actions-yarn@v2.0.0
        with:
          auth-token: ${{ secrets.NPM_TOKEN }}
          cmd: publish
      # - run: yarn publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
