# Copyright (c) TotalSoft.
# This source code is licensed under the MIT license.

name: Build and Deploy Storybook
on:
  push:
    paths: ['src/stories/**', 'src/components/**'] # Trigger the action only when files change in the folders defined here
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install and Build 🔧
        run: | # Install npm packages and build the Storybook files
          yarn install
          yarn run build-storybook
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          BRANCH: gh-pages
          FOLDER: storybuild # The folder that the build-storybook script generates files.
          CLEAN: true # Automatically remove deleted files from the deploy branch
